import { z } from 'zod'

import { FileUploadRequestSchema } from '../schemas/file-storage'

export const GUIDE_STATUS = ['draft', 'published'] as const
export const CALLOUT_TYPE = ['tip', 'note', 'warning'] as const

export const GuideStatusSchema = z.enum(GUIDE_STATUS)
export const CalloutTypeSchema = z.enum(CALLOUT_TYPE)

// Slugs that would collide with a static route under /guider, e.g. the
// editor at /guider/ny. Kept here so the service, core and the frontend all
// reject the same values.
export const RESERVED_SLUGS = ['ny'] as const

// URL-safe identifier: lowercase ascii letters, digits and single hyphens.
export const SlugSchema = z
  .string()
  .min(1)
  .max(200)
  .regex(
    /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
    'Slug may only contain lowercase letters, digits and single hyphens'
  )
  .refine(
    (slug) => !(RESERVED_SLUGS as readonly string[]).includes(slug),
    'reserved-slug'
  )

// ---------------------------------------------------------------------------
// Entities (as stored in the communication database)
// ---------------------------------------------------------------------------

export const GuideCategorySchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

export const GuideStepImageSchema = z.object({
  id: z.string().uuid(),
  stepId: z.string().uuid(),
  sortOrder: z.number().int().nonnegative(),
  // Object key in file-storage (MinIO). Bytes never pass through the
  // communication service.
  storageKey: z.string(),
  filename: z.string(),
  contentType: z.string(),
  altText: z.string(),
  caption: z.string().nullable(),
  createdAt: z.coerce.date(),
})

// Same image, enriched by core with a presigned download URL.
export const GuideStepImageWithUrlSchema = GuideStepImageSchema.extend({
  url: z.string(),
})

export const GuideStepSchema = z.object({
  id: z.string().uuid(),
  guideId: z.string().uuid(),
  sortOrder: z.number().int().nonnegative(),
  title: z.string(),
  // Sanitized HTML (p, strong, em, ul, ol, li, a, br).
  body: z.string(),
  calloutType: CalloutTypeSchema.nullable(),
  calloutText: z.string().nullable(),
  images: z.array(GuideStepImageSchema),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

export const GuideStepWithUrlsSchema = GuideStepSchema.extend({
  images: z.array(GuideStepImageWithUrlSchema),
})

export const GuideSummarySchema = z.object({
  id: z.string().uuid(),
  slug: SlugSchema,
  title: z.string(),
  description: z.string(),
  status: GuideStatusSchema,
  category: GuideCategorySchema,
  stepCount: z.number().int().nonnegative(),
  createdBy: z.string(),
  updatedBy: z.string(),
  publishedAt: z.coerce.date().nullable(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

export const GuideSchema = GuideSummarySchema.extend({
  steps: z.array(GuideStepSchema),
  // Set when the guide was resolved through guide_slug_history, i.e. the
  // caller used an old slug. Holds the slug that was requested.
  redirectedFrom: z.string().optional(),
})

export const GuideWithUrlsSchema = GuideSchema.extend({
  steps: z.array(GuideStepWithUrlsSchema),
})

// Returned by core to readers without the editor role when a guide exists
// but is still a draft, so the frontend can show a friendly notice.
export const UnpublishedGuideSchema = z.object({
  slug: SlugSchema,
  title: z.string(),
  unpublished: z.literal(true),
})

// ---------------------------------------------------------------------------
// Requests
// ---------------------------------------------------------------------------

// Image metadata sent back on save. The storage key is immutable and is never
// part of the payload; images are created through the upload endpoint.
export const StepImageInputSchema = z.object({
  id: z.string().uuid(),
  sortOrder: z.number().int().nonnegative(),
  altText: z.string().max(500),
  caption: z.string().max(500).nullable(),
})

// Step ids are generated by the client so that images can reference a step
// before and after it has been saved, and so that PUT can upsert by id.
export const StepInputSchema = z.object({
  id: z.string().uuid(),
  title: z.string().min(1).max(200),
  // Sanitized HTML. Capped so a single step cannot be used to push an
  // unbounded payload into the NVARCHAR(MAX) column.
  body: z.string().max(50_000),
  calloutType: CalloutTypeSchema.nullable().optional(),
  calloutText: z.string().max(2000).nullable().optional(),
  images: z.array(StepImageInputSchema).default([]),
})

// Pick an existing category by id, or create one by name.
export const CategoryInputSchema = z.union([
  z.object({ id: z.string().uuid() }),
  z.object({ name: z.string().min(1).max(100) }),
])

export const GuideInputBaseSchema = z.object({
  title: z.string().min(1).max(200),
  description: z.string().max(1000).default(''),
  slug: SlugSchema,
  category: CategoryInputSchema,
  status: GuideStatusSchema,
  steps: z.array(StepInputSchema),
})

type GuideInputBase = z.infer<typeof GuideInputBaseSchema>

// A guide may be saved as a draft in any state, but publishing requires at
// least one step and alt text on every image so the guide is readable
// without the images.
export const publishRules = (input: GuideInputBase, ctx: z.RefinementCtx) => {
  if (input.status !== 'published') return

  if (input.steps.length === 0) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['steps'],
      message: 'A published guide needs at least one step',
    })
  }

  input.steps.forEach((step, stepIndex) => {
    step.images.forEach((image, imageIndex) => {
      if (image.altText.trim().length === 0) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['steps', stepIndex, 'images', imageIndex, 'altText'],
          message: 'Alt text is required for published guides',
        })
      }
    })
  })
}

/**
 * Step and image ids are primary keys supplied by the client, so a duplicate
 * inside one payload would either collide on insert or silently overwrite the
 * first occurrence. Reject it up front instead.
 */
export const uniqueIdRules = (input: GuideInputBase, ctx: z.RefinementCtx) => {
  const seenStepIds = new Set<string>()
  const seenImageIds = new Set<string>()

  input.steps.forEach((step, stepIndex) => {
    const stepId = step.id.toLowerCase()
    if (seenStepIds.has(stepId)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['steps', stepIndex, 'id'],
        message: 'Step ids must be unique',
      })
    }
    seenStepIds.add(stepId)

    step.images.forEach((image, imageIndex) => {
      const imageId = image.id.toLowerCase()
      if (seenImageIds.has(imageId)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['steps', stepIndex, 'images', imageIndex, 'id'],
          message: 'Image ids must be unique',
        })
      }
      seenImageIds.add(imageId)
    })
  })
}

export const GuideInputSchema =
  GuideInputBaseSchema.superRefine(publishRules).superRefine(uniqueIdRules)
export const CreateGuideRequestSchema = GuideInputSchema
export const UpdateGuideRequestSchema = GuideInputSchema

// Service-level write payload: core adds the acting user's name.
export const ServiceGuideWriteSchema = GuideInputBaseSchema.extend({
  author: z.string().min(1).max(200),
})
  .superRefine(publishRules)
  .superRefine(uniqueIdRules)

export const ListGuidesQuerySchema = z.object({
  // Query strings arrive as text, so accept both booleans and 'true'/'false'.
  includeDrafts: z
    .union([
      z.boolean(),
      z.enum(['true', 'false']).transform((value) => value === 'true'),
    ])
    .default(false),
})

// core -> communication after the bytes have been stored in file-storage.
export const CreateStepImageRequestSchema = z.object({
  id: z.string().uuid(),
  storageKey: z.string().min(1).max(500),
  filename: z.string().min(1).max(255),
  contentType: z.string().min(1).max(100),
  altText: z.string().max(500).optional(),
  caption: z.string().max(500).nullable().optional(),
})

// frontend -> core: base64 upload plus optional metadata.
export const GuideImageUploadRequestSchema = FileUploadRequestSchema.extend({
  altText: z.string().max(500).optional(),
  caption: z.string().max(500).nullable().optional(),
})

export const UpdateGuideResponseSchema = z.object({
  guide: GuideSchema,
  // Storage keys of images removed by this save, for core to delete.
  removedStorageKeys: z.array(z.string()),
})

export const DeleteGuideResponseSchema = z.object({
  storageKeys: z.array(z.string()),
})

export const DeleteStepImageResponseSchema = z.object({
  storageKey: z.string(),
})
