import KoaRouter from '@koa/router'
import { generateRouteMetadata, logger } from '@onecore/utilities'
import { KeySystemsApi } from '../../adapters/keys-adapter'
import * as fileStorageAdapter from '../../adapters/file-storage-adapter'
import { createLogEntry, getUserName } from './helpers'

export const routes = (router: KoaRouter) => {
  router.get('/key-systems', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const page = ctx.query.page ? parseInt(ctx.query.page as string) : undefined
    const limit = ctx.query.limit
      ? parseInt(ctx.query.limit as string)
      : undefined

    const result = await KeySystemsApi.list(page, limit)

    if (!result.ok) {
      logger.error({ err: result.err, metadata }, 'Error fetching key systems')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { ...metadata, ...result.data }
  })

  router.get('/key-systems/search', async (ctx) => {
    const metadata = generateRouteMetadata(ctx, ['q', 'fields'])

    const result = await KeySystemsApi.search(ctx.query)

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { reason: 'Invalid search parameters', ...metadata }
        return
      }
      logger.error({ err: result.err, metadata }, 'Error searching key systems')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { ...metadata, ...result.data }
  })

  router.get('/key-systems/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const result = await KeySystemsApi.get(ctx.params.id)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key system not found', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error fetching key system')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.post('/key-systems', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body

    const result = await KeySystemsApi.create(payload)

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }
      if (result.err === 'conflict') {
        ctx.status = 409
        ctx.body = {
          error: 'A key system with this code already exists',
          ...metadata,
        }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error creating key system')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'creation',
      objectType: 'keySystem',
      objectId: result.data.id,
      autoGenerateDescription: true,
      entityData: result.data,
      action: 'Skapad',
    })

    ctx.status = 201
    ctx.body = { content: result.data, ...metadata }
  })

  router.put('/key-systems/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body

    const result = await KeySystemsApi.update(ctx.params.id, payload)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key system not found', ...metadata }
        return
      }
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }
      if (result.err === 'conflict') {
        ctx.status = 409
        ctx.body = {
          error: 'A key system with this code already exists',
          ...metadata,
        }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error updating key system')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'update',
      objectType: 'keySystem',
      objectId: result.data.id,
      autoGenerateDescription: true,
      entityData: result.data,
      action: 'Uppdaterad',
    })

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.delete('/key-systems/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const getResult = await KeySystemsApi.get(ctx.params.id)
    if (!getResult.ok) {
      if (getResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key system not found', ...metadata }
        return
      }
      logger.error(
        { err: getResult.err, metadata },
        'Error fetching key system before deletion'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const result = await KeySystemsApi.remove(ctx.params.id)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key system not found', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error deleting key system')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'delete',
      objectType: 'keySystem',
      objectId: ctx.params.id,
      autoGenerateDescription: true,
      entityData: getResult.data,
      action: 'Raderad',
    })

    ctx.status = 200
    ctx.body = { ...metadata }
  })

  // ==================== SCHEMA FILE ROUTES (orchestration) ====================

  /**
   * @swagger
   * /key-systems/{id}/upload-schema:
   *   post:
   *     summary: Upload a schema file for a key system
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             type: object
   *             required: [fileData]
   *             properties:
   *               fileData:
   *                 type: string
   *                 description: Base64 encoded file data
   *               fileContentType:
   *                 type: string
   *               fileName:
   *                 type: string
   *     responses:
   *       200:
   *         description: Schema file uploaded successfully
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 content:
   *                   type: object
   *                   properties:
   *                     fileId:
   *                       type: string
   *       400:
   *         description: Missing fileData
   *       404:
   *         description: Key system not found
   *       500:
   *         description: Internal server error
   */
  router.post('/key-systems/:id/upload-schema', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const { fileData, fileContentType, fileName } = ctx.request.body as {
      fileData?: string
      fileContentType?: string
      fileName?: string
    }

    if (!fileData) {
      ctx.status = 400
      ctx.body = { error: 'Missing fileData in request body', ...metadata }
      return
    }

    // Verify key system exists and get current schemaFileId
    const keySystemResult = await KeySystemsApi.get(ctx.params.id)
    if (!keySystemResult.ok) {
      if (keySystemResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key system not found', ...metadata }
        return
      }
      logger.error(
        { err: keySystemResult.err, metadata },
        'Error fetching key system for schema upload'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const keySystem = keySystemResult.data

    // Delete old schema file if one exists
    if (keySystem.schemaFileId) {
      const deleteResult = await fileStorageAdapter.deleteFile(
        keySystem.schemaFileId
      )
      if (!deleteResult.ok && deleteResult.err !== 'not_found') {
        logger.error(
          { err: deleteResult.err, fileId: keySystem.schemaFileId, metadata },
          'Error deleting old schema file'
        )
      }
    }

    // Convert base64 to buffer and upload
    const fileBuffer = Buffer.from(fileData, 'base64')
    const contentType = fileContentType || 'application/pdf'
    const originalFileName = fileName || 'schema.pdf'
    const storageFileName = `key-system-${ctx.params.id}-schema-${Date.now()}-${originalFileName}`

    const uploadResult = await fileStorageAdapter.uploadFile(
      storageFileName,
      fileBuffer,
      contentType
    )

    if (!uploadResult.ok) {
      logger.error(
        { err: uploadResult.err, metadata },
        'Error uploading schema file to storage'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const fileId = uploadResult.data.fileName

    // Update key system with new schemaFileId
    const updateResult = await KeySystemsApi.update(ctx.params.id, {
      schemaFileId: fileId,
    })

    if (!updateResult.ok) {
      // Compensate: delete the uploaded file
      await fileStorageAdapter.deleteFile(fileId)
      logger.error(
        { err: updateResult.err, metadata },
        'Error updating key system with new schemaFileId, compensating'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'update',
      objectType: 'keySystem',
      objectId: ctx.params.id,
      description: `Schema uppladdad för ${keySystem.systemCode}: ${originalFileName}`,
    })

    ctx.status = 200
    ctx.body = { content: { fileId }, ...metadata }
  })

  /**
   * @swagger
   * /key-systems/{id}/download-schema:
   *   get:
   *     summary: Get presigned download URL for a key system schema file
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *     responses:
   *       200:
   *         description: Presigned download URL
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/SchemaDownloadUrlResponse'
   *       404:
   *         description: Key system or schema file not found
   *       500:
   *         description: Internal server error
   */
  router.get('/key-systems/:id/download-schema', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const keySystemResult = await KeySystemsApi.get(ctx.params.id)
    if (!keySystemResult.ok) {
      if (keySystemResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = {
          reason: 'Key system or schema file not found',
          ...metadata,
        }
        return
      }
      logger.error(
        { err: keySystemResult.err, metadata },
        'Error fetching key system for schema download'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const keySystem = keySystemResult.data

    if (!keySystem.schemaFileId) {
      ctx.status = 404
      ctx.body = {
        reason: 'Key system or schema file not found',
        ...metadata,
      }
      return
    }

    const urlResult = await fileStorageAdapter.getFileUrl(
      keySystem.schemaFileId
    )

    if (!urlResult.ok) {
      if (urlResult.err === 'not_found') {
        ctx.status = 404
        ctx.body = {
          reason: 'Key system or schema file not found',
          ...metadata,
        }
        return
      }
      logger.error(
        { err: urlResult.err, metadata },
        'Error generating schema download URL'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { content: urlResult.data, ...metadata }
  })

  /**
   * @swagger
   * /key-systems/{id}/schema:
   *   delete:
   *     summary: Delete the schema file for a key system
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *     responses:
   *       204:
   *         description: Schema deleted successfully
   *       404:
   *         description: Key system not found
   *       500:
   *         description: Internal server error
   */
  router.delete('/key-systems/:id/schema', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const keySystemResult = await KeySystemsApi.get(ctx.params.id)
    if (!keySystemResult.ok) {
      if (keySystemResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key system not found', ...metadata }
        return
      }
      logger.error(
        { err: keySystemResult.err, metadata },
        'Error fetching key system before schema deletion'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const keySystem = keySystemResult.data

    if (keySystem.schemaFileId) {
      const deleteResult = await fileStorageAdapter.deleteFile(
        keySystem.schemaFileId
      )
      if (!deleteResult.ok && deleteResult.err !== 'not_found') {
        logger.error(
          { err: deleteResult.err, fileId: keySystem.schemaFileId, metadata },
          'Error deleting schema file from storage'
        )
        ctx.status = 500
        ctx.body = { error: 'Internal server error', ...metadata }
        return
      }
    }

    // Clear the schemaFileId on the key system
    const updateResult = await KeySystemsApi.update(ctx.params.id, {
      schemaFileId: null,
    })

    if (!updateResult.ok) {
      logger.error(
        { err: updateResult.err, metadata },
        'Error clearing schemaFileId on key system'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'update',
      objectType: 'keySystem',
      objectId: ctx.params.id,
      description: `Schema raderad för ${keySystem.systemCode}`,
    })

    ctx.status = 204
  })
}
