import KoaRouter from '@koa/router'
import { generateRouteMetadata, logger } from '@onecore/utilities'
import { KeysApi, CardsApi } from '../../adapters/keys-adapter'
import { createLogEntry } from './helpers'

export const routes = (router: KoaRouter) => {
  router.get('/keys', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const page = ctx.query.page ? parseInt(ctx.query.page as string) : undefined
    const limit = ctx.query.limit
      ? parseInt(ctx.query.limit as string)
      : undefined
    const includeKeySystem = ctx.query.includeKeySystem === 'true'

    const result = await KeysApi.list(page, limit, includeKeySystem)

    if (!result.ok) {
      logger.error({ err: result.err, metadata }, 'Error fetching keys')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { ...metadata, ...result.data }
  })

  router.get('/keys/search', async (ctx) => {
    const metadata = generateRouteMetadata(ctx, ['q', 'fields'])

    const result = await KeysApi.search(ctx.query)

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { reason: 'Invalid search parameters', ...metadata }
        return
      }
      logger.error({ err: result.err, metadata }, 'Error searching keys')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { ...metadata, ...result.data }
  })

  router.get('/keys/by-rental-object/:rentalObjectCode', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const includeLoans = ctx.query.includeLoans === 'true'
    const includeEvents = ctx.query.includeEvents === 'true'
    const includeKeySystem = ctx.query.includeKeySystem === 'true'
    const result = await KeysApi.getByRentalObjectCode(
      ctx.params.rentalObjectCode,
      { includeLoans, includeEvents, includeKeySystem }
    )

    if (!result.ok) {
      logger.error(
        { err: result.err, metadata },
        'Error fetching keys by rental object code'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.get('/cards/by-rental-object/:rentalObjectCode', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const includeLoans = ctx.query.includeLoans === 'true'
    const result = await CardsApi.getByRentalObjectCode(
      ctx.params.rentalObjectCode,
      { includeLoans }
    )

    if (!result.ok) {
      logger.error(
        { err: result.err, metadata },
        'Error fetching cards by rental object code'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.get('/cards/:cardId', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const result = await CardsApi.getById(ctx.params.cardId)

    if (!result.ok) {
      logger.error({ err: result.err, metadata }, 'Error fetching card by ID')
      ctx.status = result.err === 'not-found' ? 404 : 500
      ctx.body = {
        error:
          result.err === 'not-found'
            ? 'Card not found'
            : 'Internal server error',
        ...metadata,
      }
      return
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.get('/keys/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const result = await KeysApi.get(ctx.params.id)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key not found', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error fetching key')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.post('/keys', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body

    const result = await KeysApi.create(payload)

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error creating key')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'creation',
      objectType: 'key',
      objectId: result.data.id,
      autoGenerateDescription: true,
      entityData: result.data,
      action: 'Skapad',
    })

    ctx.status = 201
    ctx.body = { content: result.data, ...metadata }
  })

  router.put('/keys/bulk-update', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body as {
      keyIds: string[]
      updates: {
        keyName?: string
        flexNumber?: number | null
        keySystemId?: string | null
        rentalObjectCode?: string
        disposed?: boolean
        notes?: string | null
        clearNotes?: boolean
      }
    }

    const result = await KeysApi.bulkUpdate(payload.keyIds, payload.updates)

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error bulk updating keys')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    for (const keyId of payload.keyIds) {
      await createLogEntry(ctx, {
        eventType: 'update',
        objectType: 'key',
        objectId: keyId,
        description: `Massuppdaterad via bulk-uppdatering (${result.data} nycklar)`,
      })
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.put('/keys/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body

    const result = await KeysApi.update(ctx.params.id, payload)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key not found', ...metadata }
        return
      }
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error updating key')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const isDisposal = payload.disposed === true && result.data.disposed
    const action = isDisposal ? 'Kasserad' : 'Uppdaterad'

    await createLogEntry(ctx, {
      eventType: 'update',
      objectType: 'key',
      objectId: result.data.id,
      autoGenerateDescription: true,
      entityData: result.data,
      action,
    })

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.delete('/keys/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const getResult = await KeysApi.get(ctx.params.id)
    if (!getResult.ok) {
      if (getResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key not found', ...metadata }
        return
      }
      logger.error(
        { err: getResult.err, metadata },
        'Error fetching key before deletion'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const result = await KeysApi.remove(ctx.params.id)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Key not found', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error deleting key')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'delete',
      objectType: 'key',
      objectId: ctx.params.id,
      autoGenerateDescription: true,
      entityData: getResult.data,
      action: 'Raderad',
    })

    ctx.status = 200
    ctx.body = { ...metadata }
  })

  router.post('/keys/bulk-update-flex', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body

    const result = await KeysApi.bulkUpdateFlex(
      payload.rentalObjectCode,
      payload.flexNumber
    )

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error bulk updating flex')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'update',
      objectType: 'key',
      description: `Uppdaterade flex-nummer till ${payload.flexNumber} för ${payload.rentalObjectCode} (${result.data} nycklar)`,
    })

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  router.post('/keys/bulk-delete', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body as { keyIds: string[] }

    const result = await KeysApi.bulkDelete(payload.keyIds)

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error bulk deleting keys')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    for (const keyId of payload.keyIds) {
      await createLogEntry(ctx, {
        eventType: 'delete',
        objectType: 'key',
        objectId: keyId,
        description: `Raderad via massradering (${result.data} nycklar)`,
      })
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })
}
