import KoaRouter from '@koa/router'
import { generateRouteMetadata, logger } from '@onecore/utilities'
import { ReceiptsApi, KeyLoansApi } from '../../adapters/keys-adapter'
import * as fileStorageAdapter from '../../adapters/file-storage-adapter'
import { createLogEntry } from './helpers'

export const routes = (router: KoaRouter) => {
  /**
   * @swagger
   * /receipts:
   *   post:
   *     summary: Create a receipt
   *     description: Create a new receipt record for a key loan
   *     tags: [Keys Service]
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             $ref: '#/components/schemas/CreateReceiptRequest'
   *     responses:
   *       201:
   *         description: Key note created successfully
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 content:
   *                   $ref: '#/components/schemas/Receipt'
   *       400:
   *         description: Invalid request data
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/ErrorResponse'
   *       500:
   *         description: Internal server error
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/ErrorResponse'
   *     security:
   *       - bearerAuth: []
   */
  router.post('/receipts', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body

    const result = await ReceiptsApi.create(payload)

    if (!result.ok) {
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }
      if (result.err === 'conflict') {
        ctx.status = 409
        ctx.body = {
          error: 'Receipt already exists for this keyLoanId',
          ...metadata,
        }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error creating receipt')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'creation',
      objectType: 'receipt',
      objectId: result.data.id,
      autoGenerateDescription: true,
      entityData: result.data,
      action: 'Skapad',
    })

    ctx.status = 201
    ctx.body = { content: result.data, ...metadata }
  })

  /**
   * @swagger
   * /receipts/{id}:
   *   get:
   *     summary: Get a receipt by ID
   *     description: Retrieve a specific receipt by its ID
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *         description: The receipt ID
   *     responses:
   *       200:
   *         description: Successfully retrieved receipt
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 content:
   *                   $ref: '#/components/schemas/Receipt'
   *       404:
   *         description: Receipt not found
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/NotFoundResponse'
   *       500:
   *         description: Internal server error
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/ErrorResponse'
   *     security:
   *       - bearerAuth: []
   */
  router.get('/receipts/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const result = await ReceiptsApi.get(ctx.params.id)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Receipt not found', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error fetching receipt')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  /**
   * @swagger
   * /receipts/by-key-loan/{keyLoanId}:
   *   get:
   *     summary: Get receipts by key loan ID
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: keyLoanId
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *     responses:
   *       200:
   *         description: Receipts for the key loan
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 content:
   *                   type: array
   *                   items:
   *                     $ref: '#/components/schemas/Receipt'
   *       500:
   *         description: Internal server error
   */
  router.get('/receipts/by-key-loan/:keyLoanId', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const result = await ReceiptsApi.getByKeyLoan(ctx.params.keyLoanId)

    if (!result.ok) {
      logger.error(
        { err: result.err, metadata },
        'Error fetching receipts by key loan'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  /**
   * @swagger
   * /receipts/{id}:
   *   patch:
   *     summary: Update a receipt
   *     description: Update a receipt (e.g., set fileId after upload)
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *         description: The ID of the receipt to update
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             $ref: '#/components/schemas/UpdateReceiptRequest'
   *     responses:
   *       200:
   *         description: Receipt updated successfully
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 content:
   *                   $ref: '#/components/schemas/Receipt'
   *       400:
   *         description: Invalid request data
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/ErrorResponse'
   *       404:
   *         description: Receipt not found
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/NotFoundResponse'
   *       500:
   *         description: Internal server error
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/ErrorResponse'
   *     security:
   *       - bearerAuth: []
   */
  router.put('/receipts/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const payload = ctx.request.body

    const result = await ReceiptsApi.update(ctx.params.id, payload)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Receipt not found', ...metadata }
        return
      }
      if (result.err === 'bad-request') {
        ctx.status = 400
        ctx.body = { error: 'Invalid request data', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error updating receipt')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'update',
      objectType: 'receipt',
      objectId: ctx.params.id,
      autoGenerateDescription: true,
      entityData: result.data,
      action: 'Uppdaterad',
    })

    ctx.status = 200
    ctx.body = { content: result.data, ...metadata }
  })

  /**
   * @swagger
   * /receipts/{id}/upload:
   *   post:
   *     summary: Upload a file for a receipt
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             type: object
   *             required: [fileData]
   *             properties:
   *               fileData:
   *                 type: string
   *                 description: Base64 encoded file data
   *               fileContentType:
   *                 type: string
   *     responses:
   *       200:
   *         description: File uploaded successfully
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 content:
   *                   type: object
   *                   properties:
   *                     fileId:
   *                       type: string
   *       400:
   *         description: Missing fileData
   *       404:
   *         description: Receipt not found
   *       500:
   *         description: Internal server error
   */
  router.post('/receipts/:id/upload', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)
    const { fileData, fileContentType } = ctx.request.body as {
      fileData?: string
      fileContentType?: string
    }

    if (!fileData) {
      ctx.status = 400
      ctx.body = { error: 'Missing fileData in request body', ...metadata }
      return
    }

    // Verify receipt exists and get current fileId
    const receiptResult = await ReceiptsApi.get(ctx.params.id)
    if (!receiptResult.ok) {
      if (receiptResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Receipt not found', ...metadata }
        return
      }
      logger.error(
        { err: receiptResult.err, metadata },
        'Error fetching receipt for file upload'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const receipt = receiptResult.data

    // Delete old file if one exists
    if (receipt.fileId) {
      const deleteResult = await fileStorageAdapter.deleteFile(receipt.fileId)
      if (!deleteResult.ok && deleteResult.err !== 'not_found') {
        logger.error(
          { err: deleteResult.err, fileId: receipt.fileId, metadata },
          'Error deleting old receipt file'
        )
      }
    }

    // Convert base64 to buffer and upload
    const fileBuffer = Buffer.from(fileData, 'base64')
    const contentType = fileContentType || 'application/pdf'
    const storageFileName = `receipt-${ctx.params.id}-${Date.now()}.pdf`

    const uploadResult = await fileStorageAdapter.uploadFile(
      storageFileName,
      fileBuffer,
      contentType
    )

    if (!uploadResult.ok) {
      logger.error(
        { err: uploadResult.err, metadata },
        'Error uploading receipt file to storage'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const fileId = uploadResult.data.fileName

    // Update receipt with new fileId
    const updateResult = await ReceiptsApi.update(ctx.params.id, { fileId })

    if (!updateResult.ok) {
      // Compensate: delete the uploaded file
      await fileStorageAdapter.deleteFile(fileId)
      logger.error(
        { err: updateResult.err, metadata },
        'Error updating receipt with new fileId, compensating'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    // Activate the key loan if applicable
    if (receipt.keyLoanId) {
      const activateResult = await KeyLoansApi.activate(receipt.keyLoanId)
      if (!activateResult.ok) {
        logger.error(
          { err: activateResult.err, keyLoanId: receipt.keyLoanId, metadata },
          'Error activating key loan after receipt file upload'
        )
      }
    }

    ctx.status = 200
    ctx.body = { content: { fileId }, ...metadata }
  })

  /**
   * @swagger
   * /receipts/{id}:
   *   delete:
   *     summary: Delete a receipt
   *     description: Delete a receipt by ID (and associated file from MinIO)
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *         description: The ID of the receipt to delete
   *     responses:
   *       204:
   *         description: Receipt deleted successfully
   *       404:
   *         description: Receipt not found
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/NotFoundResponse'
   *       500:
   *         description: Internal server error
   *         content:
   *           application/json:
   *             schema:
   *               $ref: '#/components/schemas/ErrorResponse'
   *     security:
   *       - bearerAuth: []
   */
  router.delete('/receipts/:id', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    // Get receipt details before deleting for logging
    const receiptResult = await ReceiptsApi.get(ctx.params.id)

    if (!receiptResult.ok) {
      if (receiptResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Receipt not found', ...metadata }
        return
      }
      logger.error(
        { err: receiptResult.err, metadata },
        'Error fetching receipt before deletion'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const receipt = receiptResult.data

    // Delete the file from storage if one exists
    if (receipt.fileId) {
      const deleteFileResult = await fileStorageAdapter.deleteFile(
        receipt.fileId
      )
      if (!deleteFileResult.ok && deleteFileResult.err !== 'not_found') {
        logger.error(
          { err: deleteFileResult.err, fileId: receipt.fileId, metadata },
          'Error deleting receipt file from storage'
        )
      }
    }

    const result = await ReceiptsApi.remove(ctx.params.id)

    if (!result.ok) {
      if (result.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Receipt not found', ...metadata }
        return
      }

      logger.error({ err: result.err, metadata }, 'Error deleting receipt')
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    await createLogEntry(ctx, {
      eventType: 'delete',
      objectType: 'receipt',
      objectId: ctx.params.id,
      autoGenerateDescription: true,
      entityData: receiptResult.data,
      action: 'Raderad',
    })

    ctx.status = 200
    ctx.body = { ...metadata }
  })

  /**
   * @swagger
   * /receipts/{id}/download:
   *   get:
   *     summary: Get presigned download URL for a receipt file
   *     tags: [Keys Service]
   *     parameters:
   *       - in: path
   *         name: id
   *         required: true
   *         schema:
   *           type: string
   *           format: uuid
   *     responses:
   *       200:
   *         description: Presigned download URL
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 content:
   *                   type: object
   *                   properties:
   *                     url:
   *                       type: string
   *                     expiresIn:
   *                       type: number
   *                     fileId:
   *                       type: string
   *       404:
   *         description: Receipt or file not found
   *       500:
   *         description: Internal server error
   */
  router.get('/receipts/:id/download', async (ctx) => {
    const metadata = generateRouteMetadata(ctx)

    const receiptResult = await ReceiptsApi.get(ctx.params.id)
    if (!receiptResult.ok) {
      if (receiptResult.err === 'not-found') {
        ctx.status = 404
        ctx.body = { reason: 'Receipt or file not found', ...metadata }
        return
      }
      logger.error(
        { err: receiptResult.err, metadata },
        'Error fetching receipt for download'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    const receipt = receiptResult.data

    if (!receipt.fileId) {
      ctx.status = 404
      ctx.body = { reason: 'Receipt or file not found', ...metadata }
      return
    }

    const urlResult = await fileStorageAdapter.getFileUrl(receipt.fileId)

    if (!urlResult.ok) {
      if (urlResult.err === 'not_found') {
        ctx.status = 404
        ctx.body = { reason: 'Receipt or file not found', ...metadata }
        return
      }
      logger.error(
        { err: urlResult.err, metadata },
        'Error generating download URL'
      )
      ctx.status = 500
      ctx.body = { error: 'Internal server error', ...metadata }
      return
    }

    ctx.status = 200
    ctx.body = {
      content: { ...urlResult.data, fileId: receipt.fileId },
      ...metadata,
    }
  })
}
