services:
  # Core services
  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    ports:
      - "5010:80"
    environment:
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./core:/home/app
      - /home/app/node_modules
    depends_on:
      - property
      - work-order

  # Property service
  property:
    build:
      context: .
      dockerfile: services/property/Dockerfile
    ports:
      - "5050:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./services/property:/app
      - /app/node_modules

  # Leasing service
  leasing:
    build:
      context: .
      dockerfile: services/leasing/Dockerfile
    ports:
      - "5020:80"
    environment:
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./services/leasing:/home/app
      - /home/app/node_modules

  # Property management service
  property-management:
    build:
      context: .
      dockerfile: services/property-management/Dockerfile
    ports:
      - "5030:80"
    environment:
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./services/property-management:/home/app
      - /home/app/node_modules

  # Work order service
  work-order:
    build:
      context: .
      dockerfile: services/work-order/Dockerfile
    ports:
      - "5070:80"
    environment:
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./services/work-order:/home/app
      - /home/app/node_modules

  # Communication service
  communication:
    build:
      context: .
      dockerfile: services/communication/Dockerfile
    ports:
      - "5040:80"
    environment:
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./services/communication:/home/app
      - /home/app/node_modules

  # Internal portal backend
  internal-portal-backend:
    build:
      context: .
      dockerfile: apps/internal-portal/backend/Dockerfile
    ports:
      - "5060:80"
    environment:
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./apps/internal-portal/backend:/home/app
      - /home/app/node_modules

  # Internal portal frontend
  internal-portal-frontend:
    build:
      context: .
      dockerfile: apps/internal-portal/frontend/Dockerfile
      args:
        - BACKEND_URL=http://localhost:5060
    ports:
      - "3000:80"
    depends_on:
      - internal-portal-backend

  # Property tree app
  property-tree:
    build:
      context: .
      dockerfile: apps/property-tree/Dockerfile
      args:
        - VITE_CORE_API_URL=http://localhost:5010
        - VITE_KEYCLOAK_URL=http://localhost:8080
        - VITE_KEYCLOAK_CLIENT_ID=onecore
        - VITE_KEYCLOAK_REDIRECT_URI=http://localhost:3001
        - VITE_KEYCLOAK_REALM=onecore
    ports:
      - "3001:80"
    depends_on:
      - core

networks:
  default:
    name: onecore-network
