packages:
  - apps/*
  - apps/internal-portal/*
  - apps/leasing-portal/*
  - core
  - libs/*
  - services/*

injectWorkspacePackages: true

minimumReleaseAge: 5760
syncInjectedDepsAfterScripts:
  - build

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

minimumReleaseAgeExclude:
  - koa-okapi-router
