packages:
  - apps/*
  - apps/internal-portal/*
  - core
  - libs/*
  - services/*

injectWorkspacePackages: true

minimumReleaseAge: 5760

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
