import createClient from 'openapi-fetch'
import type { paths } from './generated/api-types' // autogenerated in package.json
import { resolve } from '@/shared/lib/env'

export const { GET, POST, PUT, DELETE, PATCH } = createClient<paths>({
  baseUrl: resolve('VITE_CORE_API_URL', 'http://localhost:5010'),
  credentials: 'include',
})

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string
  ) {
    super(message)
    this.name = 'ApiError'
  }
}
