{{/*
Copyright Bostads AB Mimer.
SPDX-License-Identifier: AGPL-3.0-only
*/}}

# ServiceAccounts
{{- range $name, $config := $.Values.components }}
{{- if kindIs "map" $config }}
{{- if $config.enabled }}
{{- if $config.serviceAccount }}
{{- if $config.serviceAccount.create }}
{{- $saName := $config.serviceAccount.name | default (include "onecore.componentName" (dict "root" $ "name" $name)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
{{ include "onecore.labels" (dict "root" $ "name" $name) | indent 4 }}
{{- if $config.serviceAccount.annotations }}
  annotations:
{{ toYaml $config.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}