import { Property } from '@/services/types'

export const sampleProperties: Property[] = [
  {
    id: "1",
    propertyObjectId: "obj-001",
    marketAreaId: "market-001",
    districtId: "district-001",
    propertyDesignationId: "designation-001",
    valueAreaId: "value-001",
    code: "PROP-001",
    designation: "Kvarter 1",
    municipality: "Stockholm",
    tract: "Centrum",
    block: "A",
    sector: "1",
    propertyIndexNumber: "123",
    congregation: "Sankt Olof",
    builtStatus: 1,
    separateAssessmentUnit: 1,
    consolidationNumber: "CONS-001",
    ownershipType: "Private",
    registrationDate: "2023-01-01",
    acquisitionDate: "2023-01-01",
  },
  {
    id: "2",
    propertyObjectId: "obj-002",
    marketAreaId: "market-002",
    districtId: "district-002",
    propertyDesignationId: "designation-002",
    valueAreaId: "value-002",
    code: "PROP-002",
    designation: "Kvarter 2",
    municipality: "Stockholm",
    tract: "Söder",
    block: "B",
    sector: "2",
    propertyIndexNumber: "456",
    congregation: "Sankt Erik",
    builtStatus: 1,
    separateAssessmentUnit: 1,
    consolidationNumber: "CONS-002",
    ownershipType: "Municipal",
    registrationDate: "2023-02-01",
    acquisitionDate: "2023-02-01",
  },
  {
    id: "3",
    propertyObjectId: "obj-003",
    marketAreaId: "market-003",
    districtId: "district-003",
    propertyDesignationId: "designation-003",
    valueAreaId: null,
    code: "PROP-003",
    designation: "Kvarter 3",
    municipality: "Stockholm",
    tract: "Väster",
    block: "C",
    sector: null,
    propertyIndexNumber: null,
    congregation: "Sankt Johannes",
    builtStatus: 1,
    separateAssessmentUnit: 1,
    consolidationNumber: "CONS-003",
    ownershipType: "Private",
    registrationDate: null,
    acquisitionDate: null,
  },
]