export const mockTenfastTenantResponse = {
  records: [
    {
      _id: 'tenant-123',
      externalId: 'P999999',
      name: {
        first: 'Test',
        last: 'Persson',
      },
      phone: '123456789',
      alternatePhones: [],
      comments: [],
      onlineInboxes: {},
      signeringsMetod: 'BankID',
      hyresvard: 'hyresvard-123',
      isCompany: false,
      idbeteckning: 'P999999',
      postadress: 'Test Street 123',
      postnummer: '12345',
      stad: 'Test City',
      borgenarer: [],
      firmatecknare: [],
      displayName: 'Test Persson',
      moms: 25,
    },
  ],
}

export const mockTenfastInvoices = [
  {
    _id: 'invoice-1',
    id: 'invoice-1',
    ocrNumber: '55123456',
    amount: 1000,
    amountPaid: 0,
    interval: {
      from: '2024-01-01',
      to: '2024-01-31',
    },
    activatedAt: '2024-01-15T10:00:00Z',
    expectedInvoiceDate: '2024-01-15T10:00:00Z',
    due: '2024-02-15T10:00:00Z',
    hyresvard: 'hyresvard-123',
    avtal: ['lease-123'],
    vatEnabled: false,
    propertyTax: false,
    simpleHyra: true,
    acceptDiff: false,
    aviseringsTyp: 'email',
    sentAutomatically: true,
    partiell: false,
    emails: [],
    ekoNotifications: [],
    skipEmail: false,
    markedAsLate: false,
    reference: 55123456,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
    __v: 0,
    late: false,
    state: 'ny',
    hyror: [
      {
        _id: 'row-1',
        amount: 1000,
        article: 'HYRAB',
        from: '2024-01-01',
        to: '2024-01-31',
        vat: 0,
        consolidationLabel: 'Hyra bostad',
        label: 'Hyra bostad',
        hyresobjekt: 'property-123',
        accountingRows: [],
      },
    ],
  },
]

export const mockTenfastInvoiceByOcrResponse = {
  records: [
    {
      _id: 'invoice-1',
      id: 'invoice-1',
      ocrNumber: '55123456',
      amount: 1000,
      amountPaid: 500,
      interval: {
        from: '2024-01-01',
        to: '2024-01-31',
      },
      activatedAt: '2024-01-15T10:00:00Z',
      expectedInvoiceDate: '2024-01-15T10:00:00Z',
      due: '2024-02-15T10:00:00Z',
      hyresvard: 'hyresvard-123',
      avtal: [
        {
          _id: 'lease-123',
          id: 'lease-123',
          hyresgaster: [
            {
              _id: 'tenant-123',
              name: {
                first: 'Test',
                last: 'Persson',
              },
              isCompany: false,
              displayName: 'Test Persson',
            },
          ],
          hyresobjekt: [
            {
              _id: 'property-123',
              nummer: '123',
              postadress: 'Test Street 123',
              skvNummer: null,
              displayName: 'Test Property',
              subType: 'apartment',
              states: [],
            },
          ],
          reference: 123456,
          stage: 'active',
          invitationsToRegister: [],
          canDelete: false,
          depositState: [],
        },
      ],
      vatEnabled: false,
      propertyTax: false,
      simpleHyra: true,
      acceptDiff: false,
      aviseringsTyp: 'email',
      sentAutomatically: true,
      partiell: false,
      emails: [],
      ekoNotifications: [],
      skipEmail: false,
      markedAsLate: false,
      reference: 55123456,
      createdAt: '2024-01-01T10:00:00Z',
      updatedAt: '2024-01-01T10:00:00Z',
      __v: 0,
      late: false,
      state: 'ny',
      hyror: [
        {
          _id: 'row-1',
          amount: 1000,
          article: 'HYRAB',
          from: '2024-01-01',
          to: '2024-01-31',
          vat: 0,
          consolidationLabel: 'Hyra bostad',
          label: 'Hyra bostad',
          hyresobjekt: 'property-123',
          accountingRows: [],
        },
      ],
    },
  ],
}

export const mockTenfastArticleResponse = {
  _id: 'HYRAB',
  label: 'Hyra bostad',
  type: 'rent',
  accountNr: '3012',
  createdAt: '2024-01-01T10:00:00Z',
  hyresvard: 'test-hyresvard',
  code: 'HYRAB',
  title: 'Hyra bostad',
  includeInContract: true,
}
