import { z } from 'zod'

export const DIRECTION = ['outbound', 'inbound'] as const
export const CHANNEL = ['sms', 'email'] as const
export const RECIPIENT_STATUS = [
  'pending',
  'sent',
  'delivered',
  'failed',
  'bounced',
  'received',
  // Scheduled sends (MIM-1897): 'scheduled' until Infobip fires the bulk
  // (delivery reports then take over), 'cancelled' if withdrawn before then.
  'scheduled',
  'cancelled',
] as const

export const DirectionSchema = z.enum(DIRECTION)
export const ChannelSchema = z.enum(CHANNEL)
export const RecipientStatusSchema = z.enum(RECIPIENT_STATUS)

export const DispatchSchema = z.object({
  id: z.string().uuid(),
  direction: DirectionSchema,
  channel: ChannelSchema,
  fromAddress: z.string(),
  subject: z.string().nullable(),
  body: z.string(),
  messageType: z.string(),
  provider: z.string(),
  triggeredByUser: z.string().nullable(),
  // Intended send time: insert time for instant sends, the target time for
  // scheduled sends. `createdAt` holds when the dispatch was queued.
  sendAt: z.coerce.date(),
  recipientCount: z.number().int().nonnegative(),
  audienceCriteria: z.string().nullable(),
  inReplyToDispatchId: z.string().uuid().nullable(),
  templateId: z.string().uuid().nullable(),
  createdAt: z.coerce.date(),
})

export const MessageRecipientSchema = z.object({
  id: z.string().uuid(),
  dispatchId: z.string().uuid(),
  contactCode: z.string().nullable(),
  toAddress: z.string(),
  status: RecipientStatusSchema,
  statusUpdatedAt: z.coerce.date(),
  externalMessageId: z.string().nullable(),
  error: z.string().nullable(),
  createdAt: z.coerce.date(),
})

export const DispatchAttachmentSchema = z.object({
  id: z.string().uuid(),
  dispatchId: z.string().uuid(),
  storageKey: z.string(),
  filename: z.string(),
  contentType: z.string(),
  createdAt: z.coerce.date(),
})

// Template `channels` and `categories` are stored as comma-separated strings
// in MSSQL but exposed here as arrays — the db adapter splits/joins.
export const TemplateSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  channels: z.array(ChannelSchema),
  subject: z.string().nullable(),
  body: z.string(),
  categories: z.array(z.string()),
  status: z.boolean(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

// Input shape for the logging adapter. Any route that wants to persist an
// outbound message calls this after the provider has accepted the send.
export const LogOutboundRecipientSchema = z.object({
  contactCode: z.string().optional(),
  toAddress: z.string(),
  externalMessageId: z.string().optional(),
  // Subset of RecipientStatusSchema: only states a new outbound row may start
  // in. delivered/bounced arrive via delivery reports, received is inbound,
  // cancelled only via the cancel flow.
  status: RecipientStatusSchema.extract([
    'pending',
    'sent',
    'failed',
    'scheduled',
  ]).optional(),
  error: z.string().optional(),
})

export const LogOutboundParamsSchema = z.object({
  // Explicit dispatch id, pre-generated by the caller when it doubles as the
  // provider bulkId (scheduled sends). Omitted -> DB generates one.
  id: z.string().uuid().optional(),
  channel: ChannelSchema,
  fromAddress: z.string(),
  subject: z.string().optional(),
  body: z.string(),
  messageType: z.string(),
  provider: z.string(),
  triggeredByUser: z.string().optional(),
  // Scheduled sends: the target delivery time. Omitted -> DB defaults to now.
  sendAt: z.coerce.date().optional(),
  // passthrough() ensures the emitted JSON schema has a `properties: {}` object,
  // which koa-okapi-router's media-type linker requires (it Object.entries() it).
  audienceCriteria: z.object({}).passthrough().optional(),
  templateId: z.string().uuid().optional(),
  recipients: z.array(LogOutboundRecipientSchema),
})

// Read-side response shapes
export const DispatchWithRecipientsSchema = z.object({
  dispatch: DispatchSchema,
  recipients: z.array(MessageRecipientSchema),
})

export const CustomerMessageSchema = z.object({
  dispatch: DispatchSchema,
  recipient: MessageRecipientSchema,
})

// --- Dispatch centre (MIM-1911) ---

// Derived dispatch-level status. Recipient rows carry raw RECIPIENT_STATUS;
// a dispatch's status is computed from its recipients (deriveDispatchStatus in
// services/communication). Lifecycle order.
export const DISPATCH_STATUS = [
  'scheduled',
  'sending',
  'delivered',
  'partially_delivered',
  'failed',
  'cancelled',
] as const
export const DispatchStatusSchema = z.enum(DISPATCH_STATUS)

// One persisted audience-filter criterion (row of dispatch_audience_criterion).
// `type` is the leasing filter key (e.g. 'buildingCodes'); `value` a single code.
export const AudienceCriterionSchema = z.object({
  type: z.string(),
  value: z.string(),
})

// Repeatable query param: single string or array -> array. Query strings arrive
// as string | string[]; koa-okapi-router does not coerce, so we do it here.
const repeatableStringParam = z
  .union([z.string(), z.array(z.string())])
  .transform((v) => (Array.isArray(v) ? v : [v]))
  .optional()

export const DispatchSearchQueryParamsSchema = z.object({
  q: z.string().optional(),
  channel: repeatableStringParam,
  messageType: repeatableStringParam,
  status: repeatableStringParam,
  source: z.enum(['manual', 'automatic']).optional(),
  triggeredByUser: z.string().optional(),
  sendAtFrom: z.string().optional(),
  sendAtTo: z.string().optional(),
  contactCode: z.string().optional(),
  minRecipients: z.coerce.number().int().nonnegative().optional(),
  audienceDistrictNames: repeatableStringParam,
  audienceBuildingCodes: repeatableStringParam,
  audienceAreaCodes: repeatableStringParam,
  sortBy: z.enum(['sendAt', 'recipientCount']).optional().default('sendAt'),
  sortOrder: z.enum(['asc', 'desc']).optional().default('desc'),
})

// A dispatch as returned by the search endpoint: dispatch row (minus the legacy
// raw-JSON audienceCriteria column) + recipient-status rollup + derived status
// + normalized audience criteria.
export const DispatchListItemSchema = DispatchSchema.omit({
  audienceCriteria: true,
}).extend({
  status: DispatchStatusSchema,
  statusSummary: z.record(RecipientStatusSchema, z.number()),
  audience: z.array(AudienceCriterionSchema),
})

// Response shapes for the scheduled-dispatch management routes, shared with
// core's communication adapter so the shapes can't drift.
export const CancelDispatchResponseSchema = z.object({
  dispatchId: z.string().uuid(),
  // 0 when the dispatch was already cancelled (idempotent no-op).
  cancelledRecipients: z.number().int().nonnegative(),
})

export const RescheduleDispatchResponseSchema = z.object({
  dispatchId: z.string().uuid(),
  sendAt: z.string(),
})
