import { z } from 'zod'

import { RENTAL_OBJECT_TYPES } from '../property/schema'

export const DIRECTION = ['outbound', 'inbound'] as const
export const CHANNEL = ['sms', 'email'] as const
export const RECIPIENT_STATUS = [
  'pending',
  'sent',
  'delivered',
  'failed',
  'bounced',
  'received',
  // Scheduled sends (MIM-1897): 'scheduled' until Infobip fires the bulk
  // (delivery reports then take over), 'cancelled' if withdrawn before then.
  'scheduled',
  'cancelled',
] as const

export const DirectionSchema = z.enum(DIRECTION)
export const ChannelSchema = z.enum(CHANNEL)
export const RecipientStatusSchema = z.enum(RECIPIENT_STATUS)

export const DispatchSchema = z.object({
  id: z.string().uuid(),
  direction: DirectionSchema,
  channel: ChannelSchema,
  fromAddress: z.string(),
  subject: z.string().nullable(),
  body: z.string(),
  messageType: z.string(),
  provider: z.string(),
  triggeredByUser: z.string().nullable(),
  // Intended send time: insert time for instant sends, the target time for
  // scheduled sends. `createdAt` holds when the dispatch was queued.
  sendAt: z.coerce.date(),
  recipientCount: z.number().int().nonnegative(),
  audienceCriteria: z.string().nullable(),
  inReplyToDispatchId: z.string().uuid().nullable(),
  templateId: z.string().uuid().nullable(),
  createdAt: z.coerce.date(),
})

export const MessageRecipientSchema = z.object({
  id: z.string().uuid(),
  dispatchId: z.string().uuid(),
  contactCode: z.string().nullable(),
  toAddress: z.string(),
  status: RecipientStatusSchema,
  statusUpdatedAt: z.coerce.date(),
  externalMessageId: z.string().nullable(),
  error: z.string().nullable(),
  createdAt: z.coerce.date(),
})

export const DispatchAttachmentSchema = z.object({
  id: z.string().uuid(),
  dispatchId: z.string().uuid(),
  storageKey: z.string(),
  filename: z.string(),
  contentType: z.string(),
  createdAt: z.coerce.date(),
})

// Template `channels` and `categories` are stored as comma-separated strings
// in MSSQL but exposed here as arrays — the db adapter splits/joins.
export const TemplateSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  channels: z.array(ChannelSchema),
  subject: z.string().nullable(),
  body: z.string(),
  categories: z.array(z.string()),
  status: z.boolean(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

// Input shape for the logging adapter. Any route that wants to persist an
// outbound message calls this after the provider has accepted the send.
export const LogOutboundRecipientSchema = z.object({
  contactCode: z.string().optional(),
  toAddress: z.string(),
  externalMessageId: z.string().optional(),
  // Subset of RecipientStatusSchema: only states a new outbound row may start
  // in. delivered/bounced arrive via delivery reports, received is inbound,
  // cancelled only via the cancel flow.
  status: RecipientStatusSchema.extract([
    'pending',
    'sent',
    'failed',
    'scheduled',
  ]).optional(),
  error: z.string().optional(),
})

export const LogOutboundParamsSchema = z.object({
  // Explicit dispatch id, pre-generated by the caller when it doubles as the
  // provider bulkId (scheduled sends). Omitted -> DB generates one.
  id: z.string().uuid().optional(),
  channel: ChannelSchema,
  fromAddress: z.string(),
  subject: z.string().optional(),
  body: z.string(),
  messageType: z.string(),
  provider: z.string(),
  triggeredByUser: z.string().optional(),
  // Scheduled sends: the target delivery time. Omitted -> DB defaults to now.
  sendAt: z.coerce.date().optional(),
  // passthrough() ensures the emitted JSON schema has a `properties: {}` object,
  // which koa-okapi-router's media-type linker requires (it Object.entries() it).
  audienceCriteria: z.object({}).passthrough().optional(),
  templateId: z.string().uuid().optional(),
  recipients: z.array(LogOutboundRecipientSchema),
})

// Read-side response shapes
export const DispatchWithRecipientsSchema = z.object({
  dispatch: DispatchSchema,
  recipients: z.array(MessageRecipientSchema),
})

export const CustomerMessageSchema = z.object({
  dispatch: DispatchSchema,
  recipient: MessageRecipientSchema,
})

// --- Dispatch centre (MIM-1911) ---

// Derived dispatch-level status. Recipient rows carry raw RECIPIENT_STATUS;
// a dispatch's status is computed from its recipients (deriveDispatchStatus in
// services/communication). Lifecycle order.
export const DISPATCH_STATUS = [
  'scheduled',
  'sending',
  'delivered',
  'partially_delivered',
  'failed',
  'cancelled',
] as const
export const DispatchStatusSchema = z.enum(DISPATCH_STATUS)

// One persisted audience-filter criterion (row of dispatch_audience_criterion).
// `type` is the leasing filter key (e.g. 'buildingCodes'); `value` a single code.
export const AudienceCriterionSchema = z.object({
  type: z.string(),
  value: z.string(),
})

// The 'objectType' criterion stores rental object types — same vocabulary the
// property service returns, so both write and read use the shared enum.
// Producers must use these values; other dialects (e.g. lease-search's
// bostad/parkering/...) are rejected on write rather than stored unmatchable.

// Repeatable query param (single value or repeated) normalized to an array and
// validated against `schema`. Query strings arrive as string | string[] and
// koa-okapi-router does not coerce, so we do it here. Passing an enum schema
// means a typo (e.g. status=bogus) 400s instead of being silently dropped.
const repeatableParam = <T extends z.ZodTypeAny>(schema: T) =>
  z
    .union([schema, z.array(schema)])
    // Cast pins the output to T[]; under a generic, Array.isArray doesn't narrow
    // the ternary cleanly and TS widens it to a union of array types.
    .transform((v) => (Array.isArray(v) ? v : [v]) as z.infer<T>[])
    .optional()

const repeatableStringParam = repeatableParam(z.string())

// Inclusive upper date bound. A date-only value ('2026-07-01') means "through
// the end of that day", so bump it to 23:59:59.999 — otherwise `sendAt <=`
// midnight would exclude everything sent that day.
// NOTE: date-only strings parse as UTC midnight, so a dispatch in the Swedish
// 00:00–02:00 window lands on the previous UTC day; day-boundary filtering is
// approximate until it keys off the Swedish-local day.
const inclusiveUpperDate = z.string().transform((s, ctx) => {
  const d = new Date(s)
  if (Number.isNaN(d.getTime())) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Invalid date' })
    return z.NEVER
  }
  if (/^\d{4}-\d{2}-\d{2}$/.test(s.trim())) d.setUTCHours(23, 59, 59, 999)
  return d
})

export const DispatchSearchQueryParamsSchema = z.object({
  q: z.string().optional(),
  channel: repeatableParam(ChannelSchema),
  messageType: repeatableStringParam,
  status: repeatableParam(DispatchStatusSchema),
  source: z.enum(['manual', 'automatic']).optional(),
  triggeredByUser: z.string().optional(),
  // Accepts date ('2026-07-01') and full ISO strings; coerces to Date and
  // rejects unparseable input with a 400 rather than reaching knex.
  sendAtFrom: z.coerce.date().optional(),
  sendAtTo: inclusiveUpperDate.optional(),
  contactCode: z.string().optional(),
  minRecipients: z.coerce.number().int().nonnegative().optional(),
  audienceDistrictNames: repeatableStringParam,
  audienceBuildingCodes: repeatableStringParam,
  // Xpand "Område" (babya.code) — distinct from kvv-areas. No current producer
  // (the audience picker stores district/kvvArea/property/building); kept for
  // criteria written by other callers.
  audienceAreaCodes: repeatableStringParam,
  audienceKvvAreaCodes: repeatableStringParam,
  audienceProperty: repeatableStringParam,
  audienceParkingAreaCodes: repeatableStringParam,
  // Composite buildingCode-staircaseCode (e.g. '504-017-01') — globally unique.
  audienceStaircaseCodes: repeatableStringParam,
  // Object-type dimension (stored criterion type 'objectType'). Special
  // matching: a dispatch with NO objectType criterion was unrestricted
  // (all types) and matches ANY value here.
  audienceObjectTypes: repeatableParam(z.enum(RENTAL_OBJECT_TYPES)),
  sortBy: z
    .enum(['sendAt', 'recipientCount', 'createdAt'])
    .optional()
    .default('sendAt'),
  sortOrder: z.enum(['asc', 'desc']).optional().default('desc'),
})

// A dispatch as returned by the search endpoint: dispatch row (minus the legacy
// raw-JSON audienceCriteria column) + recipient-status rollup + derived status
// + normalized audience criteria.
export const DispatchListItemSchema = DispatchSchema.omit({
  audienceCriteria: true,
}).extend({
  status: DispatchStatusSchema,
  statusSummary: z.record(RecipientStatusSchema, z.number()),
  audience: z.array(AudienceCriterionSchema),
})

// Response shapes for the scheduled-dispatch management routes, shared with
// core's communication adapter so the shapes can't drift.
export const CancelDispatchResponseSchema = z.object({
  dispatchId: z.string().uuid(),
  // 0 when the dispatch was already cancelled (idempotent no-op).
  cancelledRecipients: z.number().int().nonnegative(),
})

export const RescheduleDispatchResponseSchema = z.object({
  dispatchId: z.string().uuid(),
  sendAt: z.string(),
})
