name: npm-setup
description: Setup Node 20 and restore npm caches
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: '**/package-lock.json'

    # node_modules cache shared across jobs (keyed by lockfiles)
    - name: Restore node_modules cache
      id: nm
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-20-nm-${{ hashFiles('**/package-lock.json') }}

    # Only run npm ci on cache miss (keeps downstream jobs instant)
    - name: npm ci (on cache miss)
      if: steps.nm.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci --prefer-offline --no-audit --no-fund
