CREATE TABLE cmctc (
  keycmctc CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmobj CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmctk CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmctc2 CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  keycmcuh CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  keysyloc CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keysyusr CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  keylrpmt CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keyaover CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  keyaover2 CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  keycmtgr CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  keyprdel CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  keysylng CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  cmctckod VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  cmctcben VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  persorgnr VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  lcidcivno INTEGER NOT NULL,
  birthdate DATETIME NULL,
  gender TINYINT NOT NULL DEFAULT ((0)),
  civilstat TINYINT NOT NULL DEFAULT ((0)),
  fnamn VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  mname VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  enamn VARCHAR(45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  birthname VARCHAR(45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  xname VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  title VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  passno VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  region CHAR(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  avdelning VARCHAR(45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  studentno VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  nstudentno VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  sstudentno VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  studcheck TINYINT NOT NULL DEFAULT ((0)),
  startstu DATETIME NULL,
  graddate DATETIME NULL,
  createdate DATE NULL,
  avliden DATETIME NULL,
  konkurs DATETIME NULL,
  lagsokt DATETIME NULL,
  utslag DATETIME NULL,
  avhyst DATETIME NULL,
  delgiven DATETIME NULL,
  betfore DATETIME NULL,
  aggressive DATETIME NULL,
  msnp DATETIME NULL,
  wsnp DATETIME NULL,
  sletdate DATETIME NULL,
  demstatus TINYINT NOT NULL DEFAULT ((0)),
  hgffrom DATETIME NULL,
  hgftom DATETIME NULL,
  anstnr VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  cper TINYINT NOT NULL DEFAULT ((0)),
  prminbel MONEY NULL,
  forvtyp TINYINT NULL,
  resursmail TINYINT NOT NULL DEFAULT ((0)),
  aoexport TINYINT NOT NULL DEFAULT ((0)),
  mailnoti TINYINT NOT NULL DEFAULT ((0)),
  jobprcnt NUMERIC(4, 1) NULL,
  pg VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  bg VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  clearing INTEGER NULL,
  account VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  accheck TINYINT NOT NULL DEFAULT ((0)),
  accnttype TINYINT NOT NULL DEFAULT ((0)),
  bic VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  iban VARCHAR(42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  vatno VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  gln VARCHAR(13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  aouppinfo VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  aoadmmail TINYINT NOT NULL DEFAULT ((0)),
  gdprkeep TINYINT NOT NULL DEFAULT ((0)),
  gdprdate DATE NULL,
  gdprreason VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  externid VARCHAR(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  atremtype TINYINT NOT NULL DEFAULT ((0)),
  ikmestype TINYINT NOT NULL DEFAULT ((0)),
  gensoi TINYINT NOT NULL DEFAULT ((1)),
  nomerge TINYINT NOT NULL DEFAULT ((0)),
  korrvag TINYINT NOT NULL DEFAULT ((0)),
  extblocked TINYINT NOT NULL DEFAULT ((0)),
  blockads TINYINT NOT NULL DEFAULT ((0)),
  blockinfo TINYINT NOT NULL DEFAULT ((0)),
  dgophone TINYINT NOT NULL DEFAULT ((0)),
  citizen TINYINT NOT NULL DEFAULT ((0)),
  birthtime CHAR(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  otherid VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  tin VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  tincountry CHAR(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ppersorgnr VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  pfnamn VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  penamn VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  pcmctcben VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  dsguid VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  digitalcom TINYINT NOT NULL DEFAULT ((0)),
  deletemark TINYINT NOT NULL DEFAULT ((0)),
  timestamp CHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  CONSTRAINT pkcmctc PRIMARY KEY CLUSTERED (keycmctc),
-- The following FK constraints refer tables not relevant for contacts
----------------------------------------------------------------------
--  CONSTRAINT fkcmctckeyaover FOREIGN KEY(keyaover) REFERENCES aover (keyaover),
--  CONSTRAINT fkcmctckeyaover2 FOREIGN KEY(keyaover2) REFERENCES aover (keyaover),
--  CONSTRAINT fkcmctckeycmctk FOREIGN KEY(keycmctk) REFERENCES cmctk (keycmctk),
--  CONSTRAINT fkcmctckeycmcuh FOREIGN KEY(keycmcuh) REFERENCES cmcuh (keycmcuh),
--  CONSTRAINT fkcmctckeycmtgr FOREIGN KEY(keycmtgr) REFERENCES cmtgr (keycmtgr),
--  CONSTRAINT fkcmctckeylrpmt FOREIGN KEY(keylrpmt) REFERENCES lrpmt (keylrpmt),
--  CONSTRAINT fkcmctckeyprdel FOREIGN KEY(keyprdel) REFERENCES prdel (keyprdel)
)

CREATE TABLE cmtel (
  keycmtel CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmtet CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmobj CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  cmtelben CHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  main TINYINT NOT NULL DEFAULT ((0)),
  fdate DATETIME NULL,
  tdate DATETIME NULL,
  timestamp CHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  CONSTRAINT pkcmtel PRIMARY KEY CLUSTERED (keycmtel)
)

CREATE TABLE cmeml (
  keycmeml CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmemt CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmobj CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  cmemlben VARCHAR(80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  main TINYINT NOT NULL DEFAULT ((0)),
  fdate DATETIME NULL,
  tdate DATETIME NULL,
  timestamp CHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  CONSTRAINT pkcmeml PRIMARY KEY CLUSTERED (keycmeml)
)

CREATE TABLE cmadr (
  keycmadr CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycmtyp CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keydbtbl CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  keycode CHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  region CHAR(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  adress1 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress2 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress3 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress4 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress5 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress6 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress7 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress8 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress9 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  adress10 VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  fdate DATETIME NULL,
  tdate DATETIME NULL,
  timestamp CHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  CONSTRAINT pkcmadr PRIMARY KEY CLUSTERED (keycmadr)
)
