// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmtvhalsuzvwpmapfitb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tdHZoYWxzdXp2d3BtYXBmaXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDM2ODUsImV4cCI6MjA3NDE3OTY4NX0.wYUBWxexTBNL5t7TkPzZdT7-_4xkcUV2tq5PDxOEtUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});