import {
  ArrowRightLeft,
  Building,
  Calendar,
  ClipboardList,
  Contact,
  DollarSign,
  Eye,
  FileText,
  Home,
  Key,
  Lock,
  MessageSquare,
  ShieldX,
  TrendingUp,
} from 'lucide-react'

import { resolve } from '@/shared/lib/env'
import { routes } from '@/shared/routes'

import type { DashboardCard } from './types'

export const dashboardCards: DashboardCard[] = [
  {
    id: 'properties',
    title: 'Fastighetsdata',
    icon: Building,
    description: 'Hantera fastighetsbestånd och byggnader',
    path: routes.properties,
    isExternal: false,
    isDisabled: false,
  },
  {
    id: 'tenants',
    title: 'Kunder',
    icon: Contact,
    description: 'Kundregister och hyresgästinformation',
    path: routes.tenants,
    isExternal: false,
    isDisabled: false,
  },
  {
    id: 'rental',
    title: 'Uthyrning',
    icon: Home,
    description: 'Hantera uthyrning av lägenheter',
    path: resolve('VITE_INTERNAL_PORTAL', ''),
    isExternal: true,
    isDisabled: false,
  },
  {
    id: 'viewings',
    title: 'Visningar',
    icon: Calendar,
    description: 'Planera och hantera visningar',
    path: resolve('VITE_VIEWINGS', ''),
    isExternal: true,
    isDisabled: false,
  },
  {
    id: 'odoo',
    title: 'Ärendehantering (Odoo)',
    icon: MessageSquare,
    description: 'Hantera ärenden och support',
    path: resolve('VITE_ODOO_URL', ''),
    isExternal: true,
    isDisabled: false,
  },
  {
    id: 'xledger',
    title: 'Ekonomi',
    icon: DollarSign,
    description: 'Ekonomi och redovisning',
    path: resolve('VITE_XLEDGER_URL', ''),
    isExternal: true,
    isDisabled: false,
  },
  {
    id: 'passage',
    title: 'Passage',
    icon: Lock,
    description: 'Låssystem och passagekontroll',
    path: resolve('VITE_PASSAGE_URL', ''),
    isExternal: true,
    isDisabled: false,
  },
  {
    id: 'greenview',
    title: 'Greenview',
    icon: Eye,
    description: 'Översikt och rapportering',
    path: resolve('VITE_GREENVIEW_URL', ''),
    isExternal: true,
    isDisabled: false,
  },
  {
    id: 'curves',
    title: 'Curves',
    icon: TrendingUp,
    description: 'IMD',
    path: resolve('VITE_CURVES_URL', ''),
    isExternal: true,
    isDisabled: false,
  },
  {
    id: 'keys',
    title: 'Nycklar',
    icon: Key,
    description: 'Nyckelhantering',
    path: resolve('VITE_KEYS_URL', ''),
    isExternal: true,
    isDisabled: true,
  },
  {
    id: 'rental-blocks',
    title: 'Spärrar',
    icon: ShieldX,
    description: 'Hantera spärrar och begränsningar',
    path: routes.rentalBlocks,
    isExternal: false,
    isDisabled: false,
  },
  {
    id: 'turnover',
    title: 'In- och utflytt',
    icon: ArrowRightLeft,
    description: 'Hantera in- och utflyttningsprocesser',
    path: '/turnover',
    isExternal: false,
    isDisabled: true,
  },
  {
    id: 'inspections',
    title: 'Besiktningar',
    icon: ClipboardList,
    description: 'Genomför och hantera besiktningar',
    path: routes.inspections,
    isExternal: false,
    isDisabled: false,
  },
  {
    id: 'tenfast',
    title: 'Hyresadministration & avtal',
    icon: FileText,
    description: 'Hyreshantering och administration',
    path: resolve('VITE_TENFAST_URL', ''),
    isExternal: true,
    isDisabled: true,
  },
].map((card) => ({
  ...card,
  isDisabled: card.isDisabled || !card.path,
}))
