name: Lint and Type Check

on:
  pull_request:
    branches: [main, release/**, epic/**]
  push:
    branches: [main, release/**, epic/**]
  workflow_call:

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run Prettier check
        run: npm run prettier
        env:
          PRETTIER_IGNORE_PATTERN: '**/dist/**'

      - name: Run ESLint
        run: npm run lint
        env:
          ESLINT_IGNORE_PATTERN: '**/dist/**'

      - name: Run TypeScript check
        run: npm run typecheck
        env:
          TS_IGNORE_PATTERN: '**/dist/**'
